const DEFAULT_COORDINATES = {
  defaultLat: 35.68950,
  defaultLng: 139.69171,
};
const MARKERS_COUNT = 10;
const MAIN_MARKER_SIZE = [52, 52];
const MAIN_MARKER_ANCHOR = [26, 52];
const PIN_SIZE = [40, 40];
const PIN_ANCHOR = [20, 40];
const FLAT_PRICE = 1000;
const BUNGALOW_PRICE = 0;
const HOUSE_PRICE = 5000;
const PALACE_PRICE = 10000;
const HOTEL_PRICE = 3000;
const MAP_ZOOM = 12;

export {
  DEFAULT_COORDINATES,
  MARKERS_COUNT,
  MAIN_MARKER_SIZE,
  MAIN_MARKER_ANCHOR,
  PIN_SIZE,
  PIN_ANCHOR,
  FLAT_PRICE,
  BUNGALOW_PRICE,
  HOUSE_PRICE,
  PALACE_PRICE,
  HOTEL_PRICE,
  MAP_ZOOM
};
